function createfigure(xdata1, ydata1, zdata1, cdata1, X1, Y1, Z1, S1, c1)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1, CDATA1, X1, Y1, Z1, S1, C1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  CDATA1:  surface cdata
%  X1:  scatter3 x
%  Y1:  scatter3 y
%  Z1:  scatter3 z
%  S1:  scatter3 s
%  C1:  scatter3 c

%  Auto-generated by MATLAB on 30-May-2020 08:17:53
f=[F1.Cost]';
f=sortrows(f,[1,2,3]);


% Create figure
figure1 = figure;
colormap('cool');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create surf
surf(xdata1,ydata1,zdata1,cdata1,'Parent',axes1,'FaceAlpha',0.4,...
    'LineStyle',':');

% Create scatter3
scatter3(X1,Y1,Z1,S1,c1,'MarkerFaceAlpha',0.9,'MarkerFaceColor',[0 0 1],...
    'MarkerEdgeColor',[1 1 1],...
    'LineWidth',0.6);

view(axes1,[-37.5 30]);
box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'Color',[0.960784316062927 0.976470589637756 0.992156863212585],...
    'FontName','Calibri','GridColor',...
    [0.494117647058824 0.494117647058824 0.494117647058824],'XColor',[0 0 1],...
    'YColor',[0 0.498039215686275 0],'ZColor',[1 0 0]);
